# Site settings
# These are used to personalize your new site.
title: Logan Ferguson # your name here
logo: "/images/logan.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Cybersecurity (class of 2024)
  <br /><br />
  <a href="/pdf/Logan Resume">View My Resume</a>
  <br /><br />
  <a href="https://docs.google.com/document/d/1MCvZGJ01TaNcSQa-Oq_sZRttOtf_g-7g8KV-IPiSJ0U/edit?usp=sharing">View My LinkedIn Profile</a>
repository: "logon02/logon02.github.io"
github_username:  logon02 # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

